/*
 * Copyright 2026 Signal Messenger, LLC
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package org.signal.registration.screens.twofactorselection

/**
 * Two-factor authentication methods that may be presented on the two-factor selection screen. Which ones are actually
 * offered depends on what the account has registered.
 */
enum class TwoFactorMethod {
  /** A device biometric or FIDO2 passkey. */
  Passkey,

  /** A one-time code generated by the user's authenticator app. */
  AuthenticatorApp
}
