org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
kotlin.code.style=official
# Force Kotlin version and language version
kotlinVersion=2.1.0
android.kotlin.languageVersion=1.8
android.kotlin.apiVersion=1.8
